import numpy
import ctypes

name = "FORCES_CMPC"
requires_callback = False
lib = "lib/libFORCES_CMPC.so"
lib_static = "lib/libFORCES_CMPC.a"
c_header = "include/FORCES_CMPC.h"

# Parameter             | Type    | Scalar type      | Ctypes type    | Numpy type   | Shape     | Len
params = \
[("minusA_times_x0"     , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs1"       , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs2"       , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs3"       , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs4"       , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs5"       , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs6"       , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs7"       , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs8"       , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs9"       , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs10"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs11"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs12"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs13"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs14"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs15"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs16"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs17"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs18"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs19"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs20"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs21"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs22"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs23"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs24"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs25"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs26"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs27"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs28"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs29"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs30"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs31"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs32"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs33"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs34"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs35"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs36"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs37"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs38"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs39"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality_rhs40"      , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("equality1"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality2"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality3"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality4"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality5"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality6"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality7"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality8"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality9"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality10"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality11"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality12"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality13"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality14"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality15"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality16"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality17"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality18"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality19"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality20"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality21"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality22"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality23"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality24"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality25"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality26"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality27"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality28"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality29"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality30"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality31"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality32"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality33"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality34"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality35"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality36"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality37"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality38"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality39"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("equality40"          , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("cost_H1"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H2"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H3"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H4"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H5"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H6"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H7"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H8"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H9"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H10"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H11"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H12"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H13"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H14"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H15"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H16"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H17"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H18"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H19"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H20"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H21"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H22"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H23"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H24"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H25"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H26"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H27"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H28"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H29"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H30"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H31"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H32"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H33"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H34"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H35"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H36"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H37"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H38"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H39"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H40"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_H41"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("cost_f1"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f2"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f3"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f4"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f5"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f6"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f7"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f8"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f9"             , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f10"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f11"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f12"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f13"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f14"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f15"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f16"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f17"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f18"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f19"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f20"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f21"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f22"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f23"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f24"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f25"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f26"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f27"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f28"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f29"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f30"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f31"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f32"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f33"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f34"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f35"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f36"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f37"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f38"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f39"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f40"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("cost_f41"            , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("eq_D1"               , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D2"               , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D3"               , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D4"               , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D5"               , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D6"               , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D7"               , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D8"               , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D9"               , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D10"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D11"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D12"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D13"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D14"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D15"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D16"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D17"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D18"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D19"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D20"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D21"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D22"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D23"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D24"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D25"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D26"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D27"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D28"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D29"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D30"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D31"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D32"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D33"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D34"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D35"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D36"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D37"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D38"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D39"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D40"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("eq_D41"              , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("polytopic_A1"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A2"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A3"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A4"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A5"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A6"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A7"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A8"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A9"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A10"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A11"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A12"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A13"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A14"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A15"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A16"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A17"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A18"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A19"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A20"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A21"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A22"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A23"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A24"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A25"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A26"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A27"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A28"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A29"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A30"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A31"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A32"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A33"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A34"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A35"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A36"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A37"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A38"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A39"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A40"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_A41"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("polytopic_b1"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b2"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b3"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b4"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b5"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b6"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b7"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b8"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b9"        , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b10"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b11"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b12"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b13"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b14"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b15"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b16"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b17"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b18"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b19"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b20"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b21"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b22"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b23"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b24"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b25"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b26"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b27"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b28"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b29"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b30"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b31"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b32"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b33"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b34"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b35"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b36"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b37"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b38"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b39"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b40"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("polytopic_b41"       , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2)]

# Output                | Type    | Scalar type      | Ctypes type    | Numpy type   | Shape     | Len
outputs = \
[("z"                   , ""      , ""               , ctypes.c_double, numpy.float64,     ( 13,),  533)]

# Info Struct Fields
info = \
[('it', ctypes.c_int32),
('it2opt', ctypes.c_int32),
('res_eq', ctypes.c_double),
('res_ineq', ctypes.c_double),
('pobj', ctypes.c_double),
('dobj', ctypes.c_double),
('dgap', ctypes.c_double),
('rdgap', ctypes.c_double),
('gradient_lag_norm', ctypes.c_double),
('mu', ctypes.c_double),
('mu_aff', ctypes.c_double),
('sigma', ctypes.c_double),
('lsit_aff', ctypes.c_int32),
('lsit_cc', ctypes.c_int32),
('step_aff', ctypes.c_double),
('step_cc', ctypes.c_double),
('solvetime', ctypes.c_double)
]