% FORCES_CMPC - a fast solver generated by FORCESPRO v4.2.0
%
%   OUTPUT = FORCES_CMPC(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.minusA_times_x0 - column vector of length 10
%       PARAMS.equality_rhs1 - column vector of length 10
%       PARAMS.equality_rhs2 - column vector of length 10
%       PARAMS.equality_rhs3 - column vector of length 10
%       PARAMS.equality_rhs4 - column vector of length 10
%       PARAMS.equality_rhs5 - column vector of length 10
%       PARAMS.equality_rhs6 - column vector of length 10
%       PARAMS.equality_rhs7 - column vector of length 10
%       PARAMS.equality_rhs8 - column vector of length 10
%       PARAMS.equality_rhs9 - column vector of length 10
%       PARAMS.equality_rhs10 - column vector of length 10
%       PARAMS.equality_rhs11 - column vector of length 10
%       PARAMS.equality_rhs12 - column vector of length 10
%       PARAMS.equality_rhs13 - column vector of length 10
%       PARAMS.equality_rhs14 - column vector of length 10
%       PARAMS.equality_rhs15 - column vector of length 10
%       PARAMS.equality_rhs16 - column vector of length 10
%       PARAMS.equality_rhs17 - column vector of length 10
%       PARAMS.equality_rhs18 - column vector of length 10
%       PARAMS.equality_rhs19 - column vector of length 10
%       PARAMS.equality_rhs20 - column vector of length 10
%       PARAMS.equality_rhs21 - column vector of length 10
%       PARAMS.equality_rhs22 - column vector of length 10
%       PARAMS.equality_rhs23 - column vector of length 10
%       PARAMS.equality_rhs24 - column vector of length 10
%       PARAMS.equality_rhs25 - column vector of length 10
%       PARAMS.equality_rhs26 - column vector of length 10
%       PARAMS.equality_rhs27 - column vector of length 10
%       PARAMS.equality_rhs28 - column vector of length 10
%       PARAMS.equality_rhs29 - column vector of length 10
%       PARAMS.equality_rhs30 - column vector of length 10
%       PARAMS.equality_rhs31 - column vector of length 10
%       PARAMS.equality_rhs32 - column vector of length 10
%       PARAMS.equality_rhs33 - column vector of length 10
%       PARAMS.equality_rhs34 - column vector of length 10
%       PARAMS.equality_rhs35 - column vector of length 10
%       PARAMS.equality_rhs36 - column vector of length 10
%       PARAMS.equality_rhs37 - column vector of length 10
%       PARAMS.equality_rhs38 - column vector of length 10
%       PARAMS.equality_rhs39 - column vector of length 10
%       PARAMS.equality_rhs40 - column vector of length 10
%       PARAMS.equality1 - matrix of size [10 x 13]
%       PARAMS.equality2 - matrix of size [10 x 13]
%       PARAMS.equality3 - matrix of size [10 x 13]
%       PARAMS.equality4 - matrix of size [10 x 13]
%       PARAMS.equality5 - matrix of size [10 x 13]
%       PARAMS.equality6 - matrix of size [10 x 13]
%       PARAMS.equality7 - matrix of size [10 x 13]
%       PARAMS.equality8 - matrix of size [10 x 13]
%       PARAMS.equality9 - matrix of size [10 x 13]
%       PARAMS.equality10 - matrix of size [10 x 13]
%       PARAMS.equality11 - matrix of size [10 x 13]
%       PARAMS.equality12 - matrix of size [10 x 13]
%       PARAMS.equality13 - matrix of size [10 x 13]
%       PARAMS.equality14 - matrix of size [10 x 13]
%       PARAMS.equality15 - matrix of size [10 x 13]
%       PARAMS.equality16 - matrix of size [10 x 13]
%       PARAMS.equality17 - matrix of size [10 x 13]
%       PARAMS.equality18 - matrix of size [10 x 13]
%       PARAMS.equality19 - matrix of size [10 x 13]
%       PARAMS.equality20 - matrix of size [10 x 13]
%       PARAMS.equality21 - matrix of size [10 x 13]
%       PARAMS.equality22 - matrix of size [10 x 13]
%       PARAMS.equality23 - matrix of size [10 x 13]
%       PARAMS.equality24 - matrix of size [10 x 13]
%       PARAMS.equality25 - matrix of size [10 x 13]
%       PARAMS.equality26 - matrix of size [10 x 13]
%       PARAMS.equality27 - matrix of size [10 x 13]
%       PARAMS.equality28 - matrix of size [10 x 13]
%       PARAMS.equality29 - matrix of size [10 x 13]
%       PARAMS.equality30 - matrix of size [10 x 13]
%       PARAMS.equality31 - matrix of size [10 x 13]
%       PARAMS.equality32 - matrix of size [10 x 13]
%       PARAMS.equality33 - matrix of size [10 x 13]
%       PARAMS.equality34 - matrix of size [10 x 13]
%       PARAMS.equality35 - matrix of size [10 x 13]
%       PARAMS.equality36 - matrix of size [10 x 13]
%       PARAMS.equality37 - matrix of size [10 x 13]
%       PARAMS.equality38 - matrix of size [10 x 13]
%       PARAMS.equality39 - matrix of size [10 x 13]
%       PARAMS.equality40 - matrix of size [10 x 13]
%       PARAMS.cost_H1 - matrix of size [13 x 13]
%       PARAMS.cost_H2 - matrix of size [13 x 13]
%       PARAMS.cost_H3 - matrix of size [13 x 13]
%       PARAMS.cost_H4 - matrix of size [13 x 13]
%       PARAMS.cost_H5 - matrix of size [13 x 13]
%       PARAMS.cost_H6 - matrix of size [13 x 13]
%       PARAMS.cost_H7 - matrix of size [13 x 13]
%       PARAMS.cost_H8 - matrix of size [13 x 13]
%       PARAMS.cost_H9 - matrix of size [13 x 13]
%       PARAMS.cost_H10 - matrix of size [13 x 13]
%       PARAMS.cost_H11 - matrix of size [13 x 13]
%       PARAMS.cost_H12 - matrix of size [13 x 13]
%       PARAMS.cost_H13 - matrix of size [13 x 13]
%       PARAMS.cost_H14 - matrix of size [13 x 13]
%       PARAMS.cost_H15 - matrix of size [13 x 13]
%       PARAMS.cost_H16 - matrix of size [13 x 13]
%       PARAMS.cost_H17 - matrix of size [13 x 13]
%       PARAMS.cost_H18 - matrix of size [13 x 13]
%       PARAMS.cost_H19 - matrix of size [13 x 13]
%       PARAMS.cost_H20 - matrix of size [13 x 13]
%       PARAMS.cost_H21 - matrix of size [13 x 13]
%       PARAMS.cost_H22 - matrix of size [13 x 13]
%       PARAMS.cost_H23 - matrix of size [13 x 13]
%       PARAMS.cost_H24 - matrix of size [13 x 13]
%       PARAMS.cost_H25 - matrix of size [13 x 13]
%       PARAMS.cost_H26 - matrix of size [13 x 13]
%       PARAMS.cost_H27 - matrix of size [13 x 13]
%       PARAMS.cost_H28 - matrix of size [13 x 13]
%       PARAMS.cost_H29 - matrix of size [13 x 13]
%       PARAMS.cost_H30 - matrix of size [13 x 13]
%       PARAMS.cost_H31 - matrix of size [13 x 13]
%       PARAMS.cost_H32 - matrix of size [13 x 13]
%       PARAMS.cost_H33 - matrix of size [13 x 13]
%       PARAMS.cost_H34 - matrix of size [13 x 13]
%       PARAMS.cost_H35 - matrix of size [13 x 13]
%       PARAMS.cost_H36 - matrix of size [13 x 13]
%       PARAMS.cost_H37 - matrix of size [13 x 13]
%       PARAMS.cost_H38 - matrix of size [13 x 13]
%       PARAMS.cost_H39 - matrix of size [13 x 13]
%       PARAMS.cost_H40 - matrix of size [13 x 13]
%       PARAMS.cost_H41 - matrix of size [13 x 13]
%       PARAMS.cost_f1 - column vector of length 13
%       PARAMS.cost_f2 - column vector of length 13
%       PARAMS.cost_f3 - column vector of length 13
%       PARAMS.cost_f4 - column vector of length 13
%       PARAMS.cost_f5 - column vector of length 13
%       PARAMS.cost_f6 - column vector of length 13
%       PARAMS.cost_f7 - column vector of length 13
%       PARAMS.cost_f8 - column vector of length 13
%       PARAMS.cost_f9 - column vector of length 13
%       PARAMS.cost_f10 - column vector of length 13
%       PARAMS.cost_f11 - column vector of length 13
%       PARAMS.cost_f12 - column vector of length 13
%       PARAMS.cost_f13 - column vector of length 13
%       PARAMS.cost_f14 - column vector of length 13
%       PARAMS.cost_f15 - column vector of length 13
%       PARAMS.cost_f16 - column vector of length 13
%       PARAMS.cost_f17 - column vector of length 13
%       PARAMS.cost_f18 - column vector of length 13
%       PARAMS.cost_f19 - column vector of length 13
%       PARAMS.cost_f20 - column vector of length 13
%       PARAMS.cost_f21 - column vector of length 13
%       PARAMS.cost_f22 - column vector of length 13
%       PARAMS.cost_f23 - column vector of length 13
%       PARAMS.cost_f24 - column vector of length 13
%       PARAMS.cost_f25 - column vector of length 13
%       PARAMS.cost_f26 - column vector of length 13
%       PARAMS.cost_f27 - column vector of length 13
%       PARAMS.cost_f28 - column vector of length 13
%       PARAMS.cost_f29 - column vector of length 13
%       PARAMS.cost_f30 - column vector of length 13
%       PARAMS.cost_f31 - column vector of length 13
%       PARAMS.cost_f32 - column vector of length 13
%       PARAMS.cost_f33 - column vector of length 13
%       PARAMS.cost_f34 - column vector of length 13
%       PARAMS.cost_f35 - column vector of length 13
%       PARAMS.cost_f36 - column vector of length 13
%       PARAMS.cost_f37 - column vector of length 13
%       PARAMS.cost_f38 - column vector of length 13
%       PARAMS.cost_f39 - column vector of length 13
%       PARAMS.cost_f40 - column vector of length 13
%       PARAMS.cost_f41 - column vector of length 13
%       PARAMS.eq_D1 - matrix of size [10 x 13]
%       PARAMS.eq_D2 - matrix of size [10 x 13]
%       PARAMS.eq_D3 - matrix of size [10 x 13]
%       PARAMS.eq_D4 - matrix of size [10 x 13]
%       PARAMS.eq_D5 - matrix of size [10 x 13]
%       PARAMS.eq_D6 - matrix of size [10 x 13]
%       PARAMS.eq_D7 - matrix of size [10 x 13]
%       PARAMS.eq_D8 - matrix of size [10 x 13]
%       PARAMS.eq_D9 - matrix of size [10 x 13]
%       PARAMS.eq_D10 - matrix of size [10 x 13]
%       PARAMS.eq_D11 - matrix of size [10 x 13]
%       PARAMS.eq_D12 - matrix of size [10 x 13]
%       PARAMS.eq_D13 - matrix of size [10 x 13]
%       PARAMS.eq_D14 - matrix of size [10 x 13]
%       PARAMS.eq_D15 - matrix of size [10 x 13]
%       PARAMS.eq_D16 - matrix of size [10 x 13]
%       PARAMS.eq_D17 - matrix of size [10 x 13]
%       PARAMS.eq_D18 - matrix of size [10 x 13]
%       PARAMS.eq_D19 - matrix of size [10 x 13]
%       PARAMS.eq_D20 - matrix of size [10 x 13]
%       PARAMS.eq_D21 - matrix of size [10 x 13]
%       PARAMS.eq_D22 - matrix of size [10 x 13]
%       PARAMS.eq_D23 - matrix of size [10 x 13]
%       PARAMS.eq_D24 - matrix of size [10 x 13]
%       PARAMS.eq_D25 - matrix of size [10 x 13]
%       PARAMS.eq_D26 - matrix of size [10 x 13]
%       PARAMS.eq_D27 - matrix of size [10 x 13]
%       PARAMS.eq_D28 - matrix of size [10 x 13]
%       PARAMS.eq_D29 - matrix of size [10 x 13]
%       PARAMS.eq_D30 - matrix of size [10 x 13]
%       PARAMS.eq_D31 - matrix of size [10 x 13]
%       PARAMS.eq_D32 - matrix of size [10 x 13]
%       PARAMS.eq_D33 - matrix of size [10 x 13]
%       PARAMS.eq_D34 - matrix of size [10 x 13]
%       PARAMS.eq_D35 - matrix of size [10 x 13]
%       PARAMS.eq_D36 - matrix of size [10 x 13]
%       PARAMS.eq_D37 - matrix of size [10 x 13]
%       PARAMS.eq_D38 - matrix of size [10 x 13]
%       PARAMS.eq_D39 - matrix of size [10 x 13]
%       PARAMS.eq_D40 - matrix of size [10 x 13]
%       PARAMS.eq_D41 - matrix of size [10 x 13]
%       PARAMS.polytopic_A1 - matrix of size [2 x 13]
%       PARAMS.polytopic_A2 - matrix of size [2 x 13]
%       PARAMS.polytopic_A3 - matrix of size [2 x 13]
%       PARAMS.polytopic_A4 - matrix of size [2 x 13]
%       PARAMS.polytopic_A5 - matrix of size [2 x 13]
%       PARAMS.polytopic_A6 - matrix of size [2 x 13]
%       PARAMS.polytopic_A7 - matrix of size [2 x 13]
%       PARAMS.polytopic_A8 - matrix of size [2 x 13]
%       PARAMS.polytopic_A9 - matrix of size [2 x 13]
%       PARAMS.polytopic_A10 - matrix of size [2 x 13]
%       PARAMS.polytopic_A11 - matrix of size [2 x 13]
%       PARAMS.polytopic_A12 - matrix of size [2 x 13]
%       PARAMS.polytopic_A13 - matrix of size [2 x 13]
%       PARAMS.polytopic_A14 - matrix of size [2 x 13]
%       PARAMS.polytopic_A15 - matrix of size [2 x 13]
%       PARAMS.polytopic_A16 - matrix of size [2 x 13]
%       PARAMS.polytopic_A17 - matrix of size [2 x 13]
%       PARAMS.polytopic_A18 - matrix of size [2 x 13]
%       PARAMS.polytopic_A19 - matrix of size [2 x 13]
%       PARAMS.polytopic_A20 - matrix of size [2 x 13]
%       PARAMS.polytopic_A21 - matrix of size [2 x 13]
%       PARAMS.polytopic_A22 - matrix of size [2 x 13]
%       PARAMS.polytopic_A23 - matrix of size [2 x 13]
%       PARAMS.polytopic_A24 - matrix of size [2 x 13]
%       PARAMS.polytopic_A25 - matrix of size [2 x 13]
%       PARAMS.polytopic_A26 - matrix of size [2 x 13]
%       PARAMS.polytopic_A27 - matrix of size [2 x 13]
%       PARAMS.polytopic_A28 - matrix of size [2 x 13]
%       PARAMS.polytopic_A29 - matrix of size [2 x 13]
%       PARAMS.polytopic_A30 - matrix of size [2 x 13]
%       PARAMS.polytopic_A31 - matrix of size [2 x 13]
%       PARAMS.polytopic_A32 - matrix of size [2 x 13]
%       PARAMS.polytopic_A33 - matrix of size [2 x 13]
%       PARAMS.polytopic_A34 - matrix of size [2 x 13]
%       PARAMS.polytopic_A35 - matrix of size [2 x 13]
%       PARAMS.polytopic_A36 - matrix of size [2 x 13]
%       PARAMS.polytopic_A37 - matrix of size [2 x 13]
%       PARAMS.polytopic_A38 - matrix of size [2 x 13]
%       PARAMS.polytopic_A39 - matrix of size [2 x 13]
%       PARAMS.polytopic_A40 - matrix of size [2 x 13]
%       PARAMS.polytopic_A41 - matrix of size [2 x 13]
%       PARAMS.polytopic_b1 - column vector of length 2
%       PARAMS.polytopic_b2 - column vector of length 2
%       PARAMS.polytopic_b3 - column vector of length 2
%       PARAMS.polytopic_b4 - column vector of length 2
%       PARAMS.polytopic_b5 - column vector of length 2
%       PARAMS.polytopic_b6 - column vector of length 2
%       PARAMS.polytopic_b7 - column vector of length 2
%       PARAMS.polytopic_b8 - column vector of length 2
%       PARAMS.polytopic_b9 - column vector of length 2
%       PARAMS.polytopic_b10 - column vector of length 2
%       PARAMS.polytopic_b11 - column vector of length 2
%       PARAMS.polytopic_b12 - column vector of length 2
%       PARAMS.polytopic_b13 - column vector of length 2
%       PARAMS.polytopic_b14 - column vector of length 2
%       PARAMS.polytopic_b15 - column vector of length 2
%       PARAMS.polytopic_b16 - column vector of length 2
%       PARAMS.polytopic_b17 - column vector of length 2
%       PARAMS.polytopic_b18 - column vector of length 2
%       PARAMS.polytopic_b19 - column vector of length 2
%       PARAMS.polytopic_b20 - column vector of length 2
%       PARAMS.polytopic_b21 - column vector of length 2
%       PARAMS.polytopic_b22 - column vector of length 2
%       PARAMS.polytopic_b23 - column vector of length 2
%       PARAMS.polytopic_b24 - column vector of length 2
%       PARAMS.polytopic_b25 - column vector of length 2
%       PARAMS.polytopic_b26 - column vector of length 2
%       PARAMS.polytopic_b27 - column vector of length 2
%       PARAMS.polytopic_b28 - column vector of length 2
%       PARAMS.polytopic_b29 - column vector of length 2
%       PARAMS.polytopic_b30 - column vector of length 2
%       PARAMS.polytopic_b31 - column vector of length 2
%       PARAMS.polytopic_b32 - column vector of length 2
%       PARAMS.polytopic_b33 - column vector of length 2
%       PARAMS.polytopic_b34 - column vector of length 2
%       PARAMS.polytopic_b35 - column vector of length 2
%       PARAMS.polytopic_b36 - column vector of length 2
%       PARAMS.polytopic_b37 - column vector of length 2
%       PARAMS.polytopic_b38 - column vector of length 2
%       PARAMS.polytopic_b39 - column vector of length 2
%       PARAMS.polytopic_b40 - column vector of length 2
%       PARAMS.polytopic_b41 - column vector of length 2
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.z - column vector of size 533
%
%   [OUTPUT, EXITFLAG] = FORCES_CMPC(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
%    -100 - License error
%
%   [OUTPUT, EXITFLAG, INFO] = FORCES_CMPC(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.dobj      - dual objective
%       INFO.dgap      - duality gap := pobj - dobj
%       INFO.rdgap     - relative duality gap := |dgap / pobj|
%       INFO.mu        - duality measure
%       INFO.sigma     - centering parameter
%       INFO.lsit_aff  - iterations of affine line search
%       INFO.lsit_cc   - iterations of line search (combined direction)
%       INFO.step_aff  - step size (affine direction)
%       INFO.step_cc   - step size (centering direction)
%       INFO.solvetime - Time needed for solve (wall clock time)
%
% See also COPYING
